apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: postgres.kubeplus.k8s.io
spec:
  group: kubeplus.k8s.io
  names:
    kind: Postgres
    plural: postgres
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            databases:
              items:
                type: string
              type: array
            deploymentName:
              type: string
            image:
              type: string
            initcommands:
              items:
                type: string
              type: array
            replicas:
              format: int32
              type: integer
            users:
              items:
                properties:
                  password:
                    type: string
                  username:
                    type: string
                required:
                - username
                - password
                type: object
              type: array
          required:
          - deploymentName
          - image
          - replicas
          - users
          - databases
          - initcommands
          type: object
        status:
          properties:
            actionHistory:
              items:
                type: string
              type: array
            availableReplicas:
              format: int32
              type: integer
            databases:
              items:
                type: string
              type: array
            serviceIP:
              type: string
            servicePort:
              type: string
            status:
              type: string
            users:
              items:
                properties:
                  password:
                    type: string
                  username:
                    type: string
                required:
                - username
                - password
                type: object
              type: array
            verifyCommand:
              type: string
          required:
          - availableReplicas
          - actionHistory
          - users
          - databases
          - verifyCommand
          - serviceIP
          - servicePort
          - status
          type: object
      required:
      - metadata
      - spec
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
