apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator-sdk-new
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator-sdk-new
  template:
    metadata:
      labels:
        name: postgres-operator-sdk-new
    spec:
      serviceAccountName: postgres-operator-sdk-new
      containers:
        - name: postgres-operator-sdk-new
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - postgres-operator-sdk-new
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "postgres-operator-sdk-new"
