apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client25
spec:
  deploymentName: client25
  image: postgres:9.3
  replicas: 1
  users: [{"user": "devdatta", "password": "pass123"}, 
          {"user": "pallavi", "password": "pass234"}]
  databases: ["moodle"]
  commands: [ "create table moodle_data1 (items varchar(250));",
              "insert into moodle_data1 (items) values ('Moodle data1');",
              "insert into moodle_data1 (items) values ('Moodle data1');",
              "insert into moodle_data1 (items) values ('Moodle data2');",
              "GRANT ALL PRIVILEGES ON TABLE moodle_data1 TO devdatta;",
              "GRANT ALL PRIVILEGES ON TABLE moodle_data1 TO pallavi;"
            ]
