apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: operator-manager-deployment
  labels:
    app: operator-manager
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: operator-manager
  template:
    metadata:
      labels:
        app: operator-manager
    spec:
      containers:
      - name: operator-manager
        image: lmecld/operator-manager:latest
        imagePullPolicy: Always
        command: [ "/operator-manager"]
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operators.operatorcontroller.kubeplus
spec:
  group: operatorcontroller.kubeplus
  version: v1
  names:
    kind: Operator
    plural: operators
  scope: Namespaced
