apiVersion: v1
kind: ReplicationController
metadata:
  name: operator-deployer-test
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
      - name: operator-deployer
        image: operator-deployer:latest
        imagePullPolicy: Never
        command: [ "/operator-deployer", "--etcd-servers=http://localhost:2379"]

