
apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client1
spec:
  deploymentName: client1
  username: client1
  password: client1
  database: moodle
  image: postgres:9.3
  replicas: 1
  commands: ["create user client1 with password 'client1';","create database moodle with owner client1 encoding 'utf8' template=template0;"]
