apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client10
spec:
  deploymentName: client10
  username: client10
  password: client10
  database: moodle
  image: postgres:9.3
  replicas: 1
  commands: ["create user client10 with password 'client10';","create database moodle with owner client10 encoding 'utf8' template=template0;"]