
apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client2
spec:
  deploymentName: client2
  username: client2
  password: client2
  database: moodle
  image: postgres:9.3
  replicas: 1
  commands: ["create user client2 with password 'client2';","create database moodle with owner client2 encoding 'utf8' template=template0;"]
