
apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client15
spec:
  deploymentName: client15
  username: client14
  password: client14
  database: moodle
  image: postgres:9.3
  replicas: 1
  setupCommands: ["create user client14 with password 'client14';","create database moodle with owner client14 encoding 'utf8' template=template0;"]
