// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1

// PostgresListerExpansion allows custom methods to be added to
// PostgresLister.
type PostgresListerExpansion interface{}

// PostgresNamespaceListerExpansion allows custom methods to be added to
// PostgresNamespaceLister.
type PostgresNamespaceListerExpansion interface{}
