apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-operator-deployment
  labels:
    app: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      containers:
      - name: postgres-crd-v2
        image: lmecld/postgres-crd-v2:latest
        imagePullPolicy: Always
        command: [ "/postgres-crd-v2"]
#        env:
#        - name: HOST_IP
#          valueFrom:
#            fieldRef:
#              fieldPath: status.hostIP
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgreses.postgrescontroller.kubeplus
  annotations:
    platform-as-code/composition: Deployment, Service
    platform-as-code/constants: postgres-operator-implementation-details.implementation_choices
    platform-as-code/usage: postgres-operator-usage.usage
    platform-as-code/openapispec: postgres-openapispec.openapispec
spec:
  group: postgrescontroller.kubeplus
  version: v1
  names:
    kind: Postgres
    plural: postgreses
  scope: Namespaced
