// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/demo/postgrescontroller/pkg/apis/postgrescontroller/v1"
	scheme "github.com/demo/postgrescontroller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PostgresesGetter has a method to return a PostgresInterface.
// A group's client should implement this interface.
type PostgresesGetter interface {
	Postgreses(namespace string) PostgresInterface
}

// PostgresInterface has methods to work with Postgres resources.
type PostgresInterface interface {
	Create(*v1.Postgres) (*v1.Postgres, error)
	Update(*v1.Postgres) (*v1.Postgres, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Postgres, error)
	List(opts metav1.ListOptions) (*v1.PostgresList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Postgres, err error)
	PostgresExpansion
}

// postgreses implements PostgresInterface
type postgreses struct {
	client rest.Interface
	ns     string
}

// newPostgreses returns a Postgreses
func newPostgreses(c *PostgrescontrollerV1Client, namespace string) *postgreses {
	return &postgreses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the postgres, and returns the corresponding postgres object, and an error if there is any.
func (c *postgreses) Get(name string, options metav1.GetOptions) (result *v1.Postgres, err error) {
	result = &v1.Postgres{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("postgreses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Postgreses that match those selectors.
func (c *postgreses) List(opts metav1.ListOptions) (result *v1.PostgresList, err error) {
	result = &v1.PostgresList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("postgreses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested postgreses.
func (c *postgreses) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("postgreses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a postgres and creates it.  Returns the server's representation of the postgres, and an error, if there is any.
func (c *postgreses) Create(postgres *v1.Postgres) (result *v1.Postgres, err error) {
	result = &v1.Postgres{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("postgreses").
		Body(postgres).
		Do().
		Into(result)
	return
}

// Update takes the representation of a postgres and updates it. Returns the server's representation of the postgres, and an error, if there is any.
func (c *postgreses) Update(postgres *v1.Postgres) (result *v1.Postgres, err error) {
	result = &v1.Postgres{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("postgreses").
		Name(postgres.Name).
		Body(postgres).
		Do().
		Into(result)
	return
}

// Delete takes name of the postgres and deletes it. Returns an error if one occurs.
func (c *postgreses) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("postgreses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *postgreses) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("postgreses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched postgres.
func (c *postgreses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Postgres, err error) {
	result = &v1.Postgres{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("postgreses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
