apiVersion: postgrescontroller.kubeplus/v1
kind: Postgres
metadata:
  name: client25
spec:
  deploymentName: client25
  image: postgres:9.3
  replicas: 1
  users: [{"username": "devdatta", "password": "pass123"}, 
          {"username": "pallavi", "password": "pass234"},
          {"username": "shrinivas", "password": "pass1"}]
  databases: ["moodle", "wordpress"]
