apiVersion: postgres-operator-sdk.kubeplus/v1
kind: Postgres
metadata:
  name: client25
spec:
  deploymentName: client25
  image: postgres:9.3
  replicas: 1
  users: [{"username": "devdatta", "password": "pass123"}, 
          {"username": "pallavi", "password": "pass234"}]
  databases: ["moodle", "wordpress", "ecommerce"]
