apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-operator-sdk
  template:
    metadata:
      labels:
        name: postgres-operator-sdk
    spec:
      serviceAccountName: postgres-operator-sdk
      containers:
        - name: postgres-operator-sdk
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - postgres-operator-sdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "postgres-operator-sdk"
