// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	postgrescontrollerv1 "github.com/demo/postgrescontroller/pkg/apis/postgrescontroller/v1"
	versioned "github.com/demo/postgrescontroller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/demo/postgrescontroller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/demo/postgrescontroller/pkg/client/listers/postgrescontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresInformer provides access to a shared informer and lister for
// Postgreses.
type PostgresInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PostgresLister
}

type postgresInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPostgresInformer constructs a new informer for Postgres type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPostgresInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPostgresInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPostgresInformer constructs a new informer for Postgres type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPostgresInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PostgrescontrollerV1().Postgreses(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PostgrescontrollerV1().Postgreses(namespace).Watch(options)
			},
		},
		&postgrescontrollerv1.Postgres{},
		resyncPeriod,
		indexers,
	)
}

func (f *postgresInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPostgresInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *postgresInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&postgrescontrollerv1.Postgres{}, f.defaultInformer)
}

func (f *postgresInformer) Lister() v1.PostgresLister {
	return v1.NewPostgresLister(f.Informer().GetIndexer())
}
